[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Monaco"

[font.bold_italic]
family = "Monaco"

[font.italic]
family = "Monaco"

[font.normal]
family = "Monaco"

[general]
live_config_reload = true

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.cursor]
text = "#1d1f21"
cursor = "#c5c8c6"

[colors.selection]
text = "#1d1f21"
background = "#c5c8c6"

[colors.normal]
black   = "#1d1f21"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"

[colors.bright]
black   = "#666666"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0b1"
white   = "#ffffff"
